"""Purge orphaned calendar-year sla_quarterly_aggregate rows (anchor duplicates).

Quarters are project-anchored (0028): the aggregate's ``fiscal_year`` is the
CONTRACT-relative year (1, 2, 3, …). A legacy/stale writer (a contract-mgmt
binary built before the Aug-8 anchoring commit 1806c9d, still exercised by the
event-driven triggers) instead stamps the CALENDAR year (2026) via the
un-anchored ``_calendar_quarter_of`` fallback. Because the aggregate unique key
is ``(mapping_id, fiscal_year, quarter)``, those calendar-year rows do NOT
overwrite the correct anchored rows — they DUPLICATE them for the same real
quarter, shadowing settlement reads and inflating any raw aggregate view.

This deletes the calendar-year duplicates for projects that HAVE a start-date
anchor (so the anchored row is the source of truth and will regenerate on the
next anchored read). Genuinely UNDATED projects legitimately use the calendar
fallback, so their rows are LEFT ALONE. ``fiscal_year >= 1000`` unambiguously
identifies the calendar-year encoding — a contract-relative year never reaches
four digits.

ORDERING: run this only AFTER the stale un-anchored writer is stopped (redeploy
the contract service to a post-1806c9d build; remove any host crontab still
POSTing to /sla-compliance/cron/run). If the stale writer is still live it will
re-insert calendar-year rows after this migration runs.

Downgrade is an intentional no-op — the deleted rows are duplicates and are
regenerated by the current (anchored) code on the next rollup/settlement read;
there is nothing correct to restore. Mirrors 0031/0035/0036.

Revision ID: 0037_purge_calendar_aggs
Revises:     0036_backfill_pmc_ct
Create Date: 2026-08-14
"""
from __future__ import annotations

from alembic import op


revision = "0037_purge_calendar_aggs"
down_revision = "0036_backfill_pmc_ct"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Delete calendar-year (fiscal_year >= 1000) aggregate rows only for projects
    # that have a start-date anchor — those are the un-anchored DUPLICATES of the
    # correct contract-relative rows. project.projects is cross-schema (same DB).
    op.execute(
        """
        DELETE FROM contract.sla_quarterly_aggregate a
         WHERE a.fiscal_year >= 1000
           AND EXISTS (
                 SELECT 1 FROM project.projects p
                  WHERE p.id = a.project_id
                    AND p.start_date IS NOT NULL
               )
        """
    )


def downgrade() -> None:
    # Intentional no-op. The purged rows were calendar-year duplicates of the
    # anchored aggregates; the current anchored code regenerates the correct
    # rows on the next rollup/settlement read. Nothing correct to restore.
    pass
