"""
Project creation service.
"""
from typing import List, Optional
from datetime import datetime

from sqlalchemy.orm import Session

from .....domain.projects.project import Project
from .....infrastructure.db.repositories.project_repository import ProjectRepository
from .....infrastructure.db.repositories.project_status_transition_repository import (
    ProjectStatusTransitionRepository,
)
from .....infrastructure.db.repositories.vendor_repository import VendorRepository
from .....shared.datetime import ensure_aware_utc
from .....shared.service_result import ServiceResult
from .....shared.utils import normalize_string

from .audit import ACTION_CREATE, project_snapshot, record_audit
from .transitions import (
    CATEGORY_OTHERS,
    OWNER_OTHERS,
    PROJECT_CATEGORY_CHOICES,
    PROJECT_STATUS_CHOICES,
    STATUS_NEW,
    validate_owner_pair,
)


def create_project(
    db: Session,
    *,
    actor_id: Optional[str],
    name: str,
    description: Optional[str] = None,
    active: bool = True,
    public: bool = False,
    status_explanation: Optional[str] = None,
    parent_id: Optional[str] = None,
    status: str = STATUS_NEW,
    owner: Optional[str] = None,
    owner_other: Optional[str] = None,
    category: Optional[str] = None,
    category_other: Optional[str] = None,
    category_other_reason: Optional[str] = None,
    vendor_ids: Optional[List[str]] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
) -> ServiceResult[Project]:
    """Create a new (non-version) project.

    The public handle (uuid) and the display code (project_code) are both
    server-generated by the repository. Commits the transaction on success.
    """
    name = normalize_string(name)
    if not name or len(name) > 255:
        return ServiceResult.fail(
            error="Invalid name. Must be 1-255 characters.",
            error_type="validation_error",
        )

    if description and len(description) > 5000:
        return ServiceResult.fail(
            error="Description too long. Maximum 5000 characters.",
            error_type="validation_error",
        )

    if status_explanation and len(status_explanation) > 5000:
        return ServiceResult.fail(
            error="Status explanation too long. Maximum 5000 characters.",
            error_type="validation_error",
        )

    # Status validation against the project_status_transitions catalog. The
    # in-code PROJECT_STATUS_CHOICES set still exists as a backstop for the
    # case where the catalog hasn't been seeded (e.g. tests on a fresh
    # in-memory DB before init_db has run); the table is the primary truth
    # whenever it has rows.
    transition_repo = ProjectStatusTransitionRepository(db)
    catalog_statuses = transition_repo.known_to_statuses()
    valid_statuses = catalog_statuses if catalog_statuses else list(PROJECT_STATUS_CHOICES)
    if status not in valid_statuses:
        return ServiceResult.fail(
            error=f"Invalid status '{status}'. Allowed: {', '.join(valid_statuses)}",
            error_type="invalid_status",
        )

    if category is not None and category not in PROJECT_CATEGORY_CHOICES:
        return ServiceResult.fail(
            error=f"Invalid category '{category}'.",
            error_type="validation_error",
        )

    # "others" category: categoryOther is required, non-empty, <= 255 chars.
    # For non-'others' categories the field must be None (accidentally setting
    # it is a client bug we reject with 422 rather than silently storing).
    if category == CATEGORY_OTHERS:
        co = normalize_string(category_other) if category_other else ""
        if not co:
            return ServiceResult.fail(
                error="categoryOther is required when category is 'others'.",
                error_type="validation_error",
            )
        if len(co) > 255:
            return ServiceResult.fail(
                error="categoryOther must be 1-255 characters.",
                error_type="validation_error",
            )
        category_other = co
        # categoryOtherReason: required when category='others', max 1000.
        cor = normalize_string(category_other_reason) if category_other_reason else ""
        if not cor:
            return ServiceResult.fail(
                error="categoryOtherReason is required when category is 'others'.",
                error_type="validation_error",
            )
        if len(cor) > 1000:
            return ServiceResult.fail(
                error="categoryOtherReason must be 1-1000 characters.",
                error_type="validation_error",
            )
        category_other_reason = cor
    else:
        if category_other is not None and normalize_string(category_other) != "":
            return ServiceResult.fail(
                error="categoryOther may only be provided when category is 'others'.",
                error_type="validation_error",
            )
        category_other = None
        if category_other_reason is not None and normalize_string(category_other_reason) != "":
            return ServiceResult.fail(
                error="categoryOtherReason may only be provided when category is 'others'.",
                error_type="validation_error",
            )
        category_other_reason = None

    # "Must be in the future" is enforced by the Pydantic schema; skip the
    # duplicate check here to avoid naive/aware datetime comparison bugs.
    start_utc = ensure_aware_utc(start_date)
    end_utc = ensure_aware_utc(end_date)
    # Inclusive: end_date == start_date is allowed (single-day projects).
    if start_utc is not None and end_utc is not None and end_utc < start_utc:
        return ServiceResult.fail(
            error="end_date cannot be before start_date",
            error_type="validation_error",
        )

    # Owner is a DIVISION code (built-in or user-added) supplied by the
    # FE division picker. REQUIRED on create. When owner == 'others' the
    # FE captures a free-text label and sends it as `ownerOther`; that
    # label is validated here and persisted into the divisions catalog
    # below (so the next project-owner dropdown shows the new option).
    owner, owner_other, owner_err = validate_owner_pair(
        owner, owner_other, require_owner=True, db=db,
    )
    if owner_err:
        return ServiceResult.fail(error=owner_err, error_type="validation_error")

    repo = ProjectRepository(db)
    vendor_repo = VendorRepository(db)

    if parent_id is not None and not repo.exists_by_id(parent_id):
        return ServiceResult.fail(
            error=f"Parent project with ID {parent_id} does not exist",
            error_type="not_found",
        )

    # De-duplicate + validate vendor IDs.
    # Doc 25: each entry can be a UUID OR a ``VN-...`` code. We resolve
    # to canonical UUIDs first, surface the original token in the error
    # message if any fail to resolve, then validate the resolved set
    # against the live (active, non-deleted) catalogue.
    if vendor_ids:
        unique_input = list(dict.fromkeys(vendor_ids))  # preserve order, unique
        # Per-token resolution so we can name the bad input verbatim.
        resolved_pairs = [(token, vendor_repo.resolve_id(token)) for token in unique_input]
        unresolved = [t for (t, rid) in resolved_pairs if rid is None]
        if unresolved:
            return ServiceResult.fail(
                error=f"Unknown vendor(s): {', '.join(unresolved)}",
                error_type="validation_error",
            )
        canonical_ids = [rid for (_t, rid) in resolved_pairs]
        ok_ids = set(vendor_repo.existing_active_ids(canonical_ids))
        # Map back to caller tokens for the error so VN-codes show up
        # rather than UUIDs the caller didn't send.
        missing_tokens = [
            t for (t, rid) in resolved_pairs if rid not in ok_ids
        ]
        if missing_tokens:
            return ServiceResult.fail(
                error=f"Unknown or inactive vendor(s): {', '.join(missing_tokens)}",
                error_type="validation_error",
            )
        vendor_ids = canonical_ids
    else:
        vendor_ids = []

    try:
        project = repo.create(
            name=name,
            description=description,
            active=active,
            public=public,
            status_explanation=status_explanation,
            parent_id=parent_id,
            status=status,
            owner=owner,
            owner_other=owner_other,
            category=category,
            category_other=category_other,
            category_other_reason=category_other_reason,
            start_date=start_date,
            end_date=end_date,
            created_by=actor_id,
        )

        # Attach vendors (repository flushes but does not commit).
        if vendor_ids:
            vendor_repo.set_project_vendors(project.id, vendor_ids)
            # Refresh the domain object's vendor list for the response.
            project.vendors = vendor_repo.list_project_vendors(project.id)

        # NOTE: pre-doc-20, this point used to upsert a divisions row from
        # the user's free-text ``owner_other`` label (so the next project
        # could pick it from the dropdown). That auto-create path was
        # removed — it produced rogue divisions like 'admin' / 'test' from
        # one-off project labels and tester-reported pollution of the
        # picker. The catalog is now strictly admin-managed via
        # POST /api/v3/master/divisions/create. The label still lives on
        # the project row's owner_other column for display.

        record_audit(
            db,
            project_id=project.id,
            actor_id=actor_id,
            action=ACTION_CREATE,
            before=None,
            after=project_snapshot(project),
        )

        db.commit()
        return ServiceResult.ok(project)

    except Exception as e:
        db.rollback()
        return ServiceResult.fail(
            error=f"Failed to create project: {str(e)}",
            error_type="internal_error",
        )
